### ISSUE TITLE
Display the Changelog more prominently

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#2049]
### Implement a changelog that pops up after every release. 
There will have to be two changelogs. One for the operator, one for end users. This is because action required items, some backend items and bugfixes should not be shown to end users.

### Point for discussion
How do we differentiate on the technical side between operator users and end users? 

### Design 
(will be scrollable in interface, exemplary content)
![image](https://user-images.githubusercontent.com/49145827/75657075-b072fe80-5c65-11ea-88a0-0a7b8572a096.png)

**Comment by cschieder** [comment]
> There will have to be two changelogs. One for the operator, one for end users. This is because action required items, some backend items and bugfixes should not be shown to end users.
> 
> How do we differentiate on the technical side between operator users and end users?

Any ideas for this? I still think the changelog would be a nice feature @kubermatic/ui-team

**Comment by floreks** [comment]
We've discussed the approach and architecture with @maciaszczykm and there are a couple of remarks:
- changelog will be a yaml/json file bundled in the application similar to the UI config file
- based on the general changelog (as prepared lately by @xrstf), we (the sig-ui) will take only the most important information and prepare a PR with the new changelog file for the UI. NOTE: It should be done as a last PR before the release and we should make sure to add this step to our release procedure.
- @cschieder there should be i.e. a checkbox to disable the changelog popup so it doesn't bother users every time they log-in. I'd make it selected by default. We'll also provide additional settings in the user panel related to this so that users can disable it at any time. After the new release, it will be invalid and a new changelog will appear anyway until disabled again.
- it should be possible to embed links inside text messages that could point user i.e. to the documentation of specific feature

At first, we will provide a simple version that could be extended in the future.

Possible future improvements:
- possibility to embed images (thumbnails that could be enlarged) for specific changes
- possibility to embed videos (similar to images)

Any additional input regarding this feature is welcome.

**Comment by cschieder** [comment]
@floreks Actually, should we even show the changelog multiple times? If we make it checked by default then I'm not sure if we even need the box, we could just show it only once in general.

We should also offer a way to check out Changelog after closing the dialog, e. g. through a Help section dropdown point - Link to Github or reopen the dialog?

**Comment by floreks** [comment]
We can do that. Can you then prepare some draft on how to access the changelog after closing it? We will mark it as read after each release and not display it automatically after the first time.

**Comment by cschieder** [comment]
I would add it as a point to the Help Section #1934
