### ISSUE TITLE
Cluster State different for shared users

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#2866]
**What happened?**:

**Important:** In my KKP setup, I have email restrictions in place. Only the original owner (the right side in the screenshot below) can access my Seeds and Datacenters, the other user (on the left side, who was shared the project with) has no access to the datacenters.

I created a project, added a few clusters to it and then shared the project with another user and gave them the "editor" role in my project. If I log into another browser as said editor user, the clusters are shown with a yellow dot and the region names are missing.

![screenshot-2020-12-10-143653](https://user-images.githubusercontent.com/127499/101779423-8c4a2500-3af5-11eb-8221-e38e4d79084c.png)

From what I can see, the role does not matter. Even if the user is added as an Owner, they still cannot see all cluster details.

Also, the editor user cannot even open any cluster. On clicking any row in the table, nothing happens. The browser console logs

![screenshot-2020-12-10-144242](https://user-images.githubusercontent.com/127499/101779844-0da1b780-3af6-11eb-854b-19761dcaa8f6.png)

This is most likely because the user has no access to the datacenters.

**What should happen?**:
I shoulld not see misleading information (the yellow dot). That I cannot see datacenter names kind of makes sense, given the `requiredEmailDomains` restrictions in my system, but then the UI should not even let me click on the row. Or somehow tell me "You got these clusters shared with you, but you have no access to the datacenters.".

**How to reproduce?**:
See above.

**Environment**
- UI Version: v2.15.6
- API Version: v2.15.6
- Domain: Captain
- Others: Firefox on Ubuntu

**Comment by maciaszczykm** [comment]
I think https://github.com/kubermatic/dashboard/issues/2438 will improve the situation as the seed param is already removed from the path (that probably was the cause of failed redirection) and we are not using seeds in every request to the API. If that is okay for everyone I would wait until https://github.com/kubermatic/dashboard/issues/2438 will be done as it gives us advantage.

I have tested it on dev with the same email domains and it works, that makes the scale of the bug a little bit smaller.

**Comment by maciaszczykm** [comment]
I've checked it again and the behaviour has changed. Right now if we will add an user that do not have access to the datacenters he will not be able to see anything:

<img width="1582" alt="Zrzut ekranu 2021-07-27 o 10 16 58" src="https://user-images.githubusercontent.com/2823399/127120934-fb68e0ca-559d-4e07-8a2d-a3c6fe3f1a09.png">

Note: `marcin-test` is a datacenter with `requiredEmailDomains` set.

<img width="1278" alt="Zrzut ekranu 2021-07-27 o 10 20 05" src="https://user-images.githubusercontent.com/2823399/127121197-d412183d-7a9b-4d40-bac8-85cc55d988bd.png">

Here is what owner of the project sees. Only one of the cluster datacenters has `requiredEmailDomains` set.

**Comment by maciaszczykm** [comment]
I will see how we can improve. However, it might be hard as we are using 404 in case when there is no datacenter and if user doesn't have access to it.

**Comment by maciaszczykm** [comment]
Things to consider:
1. At the moment `error 404: datacenter not found` is returned from the list clusters endpoint when there is at least one cluster that has `requiredEmailDomains` different than the user email domain. It's not good because user is not able to work with other clusters. We could change it to filter out clusters that user doesn't have access to but keep the ones that should be accessible. If we would do that it would be also good to show some info about filtered out clusters.
2. I think it was decided to use 404 error if there is no datacenter and if user doesn't have access to it to simplify things or for some security reason. This is not perfect though as in the UI there is no information what is happening.
3. Perhaps we should think about adding a new endpoint that will allow to check if user meets the required email domain of cluster's datacenter. Then we can display some more details in the UI.

@kubermatic/sig-api @kubermatic/sig-ui @shaase-ctrl I'm adding you into the loop to discuss what should be the actual behaviour here so we can work on it.

**Comment by shaase-ctrl** [comment]
Thanks for involving me and thanks for the solid description. 
1. From my point of view the project access and datacenter access must not be related. 
- Therefore the user invited needs to be able to work with the cluster
2. But we have to consider larger scale customers and such behaviour might be the result of various dependencies: 
- Admin did not configure the user who was invited for access properly (mistake)
- project owner is not allowed to invite users (wanted behaviour by admin)
Considering the current state of customer projects I would opt for the mistake rather then the wanted restrictive behaviour. 

@maciaszczykm I would go for number 3, display the needed information to proceed as we can circumvent RBAC accidents and no user is left in the dark as @xrstf suggested.

**Comment by maciaszczykm** [comment]
>From my point of view the project access and datacenter access must not be related. Therefore the user invited needs to be able to work with the cluster

Datacenter access is not related to the project access but it matters when it comes to cluster access. Some time ago we have simplified the API and the UI a lot by removing the `seed` param from the endpoint paths but datacenters are still a resource that is used when listing the clusters (to be able to filter by datacenter region) or in the cluster details (there are many use cases in that view). To make it totally independent we would need to adjust how `requiredEmailDomains` works. At the moment it is not possible at all to access the datacenter if your email domain does not meet criteria, and without datacenter access we cannot get all the cluster data. Should we (in some cases) allow access to the datacenters even if the `requiredEmailDomains` criteria is not met for the user? What would you suggest? 

If we would check that user has access to all of the clusters in the project during inviting him there is still a possibility that someone will create a cluster with `requiredEmailDomains` that will not match email domain of some users. There is also a risk of datacenter's `requiredEmailDomains` being modified. The verification would need to happen not only during adding new users to the project but also during the cluster creation and datacenter edits. It's quite complex thing to do.

> @maciaszczykm I would go for number 3, display the needed information to proceed as we can circumvent RBAC accidents and no user is left in the dark as @xrstf suggested.

Sounds like a good thing to start with. However, I was thinking a bit more about it and perhaps changing the  `error 404: datacenter not found` message that comes from the API to something like `error: you are not authorized to list clusters because your account doesn't meet the required email domain criteria` would be better for the beginning? The output would be the same as it will give information to the user what went wrong.

**Comment by kgroschoff** [comment]
I'm not deeply into this topic, but I have some thoughts (might be wrong though):

I think it should always be possible to list the clusters that are available and those that aren't matching, shouldn't be in the list. Just returning a 404 if one of x clusters has not the correct access rights, feels a bit exaggerated to me. 
It would be nice, if there would be a hint that there are more, but on the other hand the `requiredEmailDomains` criteria is exactly for the case, that some users shouldn't get access to this clusters. 🤔 

However, for the beginning, I guess it would be a good idea to start with changing the error message @maciaszczykm .

**Comment by lsviben** [comment]
I agree with @kgroschoff , its a bug that we return 404 when the user cant access just one cluster due to `requiredEmailDomains`, we should just return the filtered list of clusters.

 If the user is confused why this is happening, probably they can connect the dots and realize that the only clusters not available are those in datacenters with `requiredEmailDomains` set. 
 
Another option I see if we want to circumvent admin setup mistakes is to start treating the `requiredEmailDomains` in the Datacenter as just "outside user cannot create a cluster in this Datacenter", instead of "outside user cannot view/touch anything related to this Datacenter" . Then users in a project could use all project's clusters based on their project permission level. But I dont know if that makes business sense.

**Comment by maciaszczykm** [comment]
I agree with you, @kgroschoff and @lsviben, that endpoint will need change.

> Another option I see if we want to circumvent admin setup mistakes is to start treating the requiredEmailDomains in the Datacenter as just "outside user cannot create a cluster in this Datacenter", instead of "outside user cannot view/touch anything related to this Datacenter" . Then users in a project could use all project's clusters based on their project permission level. But I dont know if that makes business sense.

@lsviben I'm not sure if I get it correctly but I think we already treat `requiredEmailDomains` in the datacenter as "outside user cannot create a cluster in this Datacenter" and "outside user cannot view/touch anything related to this Datacenter" at the same time. If you don't meet the `requiredEmailDomains` requirement then the datacenter will be not displayed in the wizard at all. The problem is that one user might have different email domain than the other and then he can create a cluster which the second user will not be able to use. All happens in the same project.

**Comment by lsviben** [comment]
> > Another option I see if we want to circumvent admin setup mistakes is to start treating the requiredEmailDomains in the Datacenter as just "outside user cannot create a cluster in this Datacenter", instead of "outside user cannot view/touch anything related to this Datacenter" . Then users in a project could use all project's clusters based on their project permission level. But I dont know if that makes business sense.
> 
> @lsviben I'm not sure if I get it correctly but I think we already treat `requiredEmailDomains` in the datacenter as "outside user cannot create a cluster in this Datacenter" and "outside user cannot view/touch anything related to this Datacenter" at the same time. If you don't meet the `requiredEmailDomains` requirement then the datacenter will be not displayed in the wizard at all. The problem is that one user might have different email domain than the other and then he can create a cluster which the second user will not be able to use. All happens in the same project.

For this i meant that we can change
From:
 "outside user cannot create a cluster in this Datacenter" and "outside user cannot view/touch anything related to this Datacenter" at the same time.
To: "outside user cannot create a cluster in this Datacenter"

If that makes sense for the business case @shaase-ctrl mentioned (Admin did not configure the user who was invited for access properly (mistake)), but I dont know if that is ok because the user could manage the cluster from a datacenter he has no access to. 

Personally I would just fix the bug for now, and think about how we want to divide/manage datacenter vs cluster permissions for the future

**Comment by maciaszczykm** [comment]
I think the issue if fixed already. Here is what the owner sees:

<img width="1917" alt="Zrzut ekranu 2021-08-10 o 11 17 40" src="https://user-images.githubusercontent.com/2823399/128841753-84f5cf02-86ac-4c19-924a-c5f43490879e.png">

And here is what invited user with different email domain sees:

<img width="1917" alt="Zrzut ekranu 2021-08-10 o 11 18 00" src="https://user-images.githubusercontent.com/2823399/128841801-77b4590e-155e-4fd5-b82a-0d50562dedff.png">

As you can see the cluster with restricted datacenter got filtered out. There are no more errors or invalid statuses.

It was implemented in https://github.com/kubermatic/kubermatic/pull/7440.

Please reopen in case of any doubts or remarks.
