### ISSUE TITLE
Last label dissapears from form after pressing enter

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#2891]
**What happened?**: Last label is lost on each key press.

**What should happen?**: Labels should not be deleted in this case.

**How to reproduce?**:
1. Open the project creation dialog.
1. Leave name field empty.
1. Use tab/mouse to switch to label field.
1. Fill some labels.
1. Click enter key.

**Environment**
- UI Version: Master.
- API Version: Master.
- Domain: Dev and locally.
- Others: Chrome on macOS.

**Comment by kgroschoff** [comment]
Issue slightly "changed" atm: 
Currently nothing will happen when pressing enter, which is (kind of) the expected behavior. This is due to a `onkeypress="return event.keyCode != 13;"` on the input fields of the label form.
Due to this there is a "new" problem: We now want to allow the user to submit a form by pressing enter. When the user now adds a new project with a name and tabs to the labels form, entering some data and wants to submit by pressing enter: nothing happens. 😅
