### ISSUE TITLE
Replace "MLA" prefix with "User Cluster" 

### ISSUE THREAD

**Issue by jiachengxu** [kubermatic/dashboard#3426]
Currently, we have `MLA` prefixed for all MLA-related options, and we can replace it with `User Cluster` to make it clear to both KKP admins and users.

Admin Panel:
- [ ] MLA Logging -> User Cluster Logging
- [ ] MLA Monitoring -> User Cluster Monitoring

Cluster Creation Page:
- [ ] MLA Logging -> User Cluster Logging
- [ ] MLA Monitoring -> User Cluster Monitoring

Cluster Details Tabs:
- [ ] MLA Alertmanager Config -> Alertmanger Config or User Cluser Alertmanager Config?

For the Cluster Details Tabs, I am not sure if we should have `User Cluster` prefix since that will make the tab name quite long.
Any thought? @shaase-ctrl @kgroschoff @rastislavs

**Comment by kgroschoff** [comment]
Since we are introducing the new link into the Alertmanager Config tab, I was wondering if it would make sense to rename it to just `MLA Alertmanager` (and MLA will be replaced by the new prefix :trollface: )
WDYT?

**Comment by jiachengxu** [comment]
> Since we are introducing the new link into the Alertmanager Config tab, I was wondering if it would make sense to rename it to just MLA Alertmanager (and MLA will be replaced by the new prefix :trollface: ), as it then isn't only including the config part
WDYT?
@kgroschoff You are right, this sounds good to me :)

**Comment by kgroschoff** [comment]
Regarding the renaming itself I'm open for everything. Just don't know what fits best, I would leave that up to you. 😀

**Comment by rastislavs** [comment]
We agreed with @shaase-ctrl that we want to have the `User Cluster` prefix instead of MLA everywhere because:
 - MLA is just our "internal" abbreviation but makes no sense to newcomers
 - we want to be clear that we will have 2 distinct Monitoring stacks: `Seed Cluster` and `User Cluster`
 - if we repeat it everywhere, the users will learn it and will know what it means

So based on that, for the cluster details tab,  we should go with the `User Cluster Alertmanager`
