### ISSUE TITLE
Fix Version in Footer

### ISSUE THREAD

**Issue by xrstf** [kubermatic/dashboard#3641]
**What happened?**:
The dashboard on dev shows that it's 

![screenshot-2021-08-30-111713](https://user-images.githubusercontent.com/127499/131316751-bc1e9555-bdd9-4d67-8568-a3851c364103.png)

It should show "v2.18.0-dev". This is probably because the version on dev was _also_ tagged as the weekly release and the weekly release job incorrectly determined the version to use.

**What should happen?**:
The footer must read either the tagged version or the _next_ upcoming minor version (i.e. 2.18 at this moment).

**How to reproduce?**:

**Environment**
- UI Version:
- API Version:
- Domain:
- Others:

**Comment by maciaszczykm** [comment]
I think it's because the 2.14 tag was the last one created directly from master. Since then we had been using release branches and it seems that they are not recognized.

**Comment by maciaszczykm** [comment]
<img width="459" alt="Zrzut ekranu 2021-11-15 o 09 27 31" src="https://user-images.githubusercontent.com/2823399/141747636-9b8ddca3-35e9-4b20-9574-4536891bc63d.png">

As you can see v2.18.0 was tagged from a commit that exists in master and it is visible in the footer. It doesn't see the v2.18.1 and v2.18.2 though. Probably because minor releases are created from the release branches where there are differences that the tool that we use is not able to process. The tool that we use is based on `git desribe` command:

```
➜ git describe upstream/master --abbrev=0
v2.18.0-rc.0

➜ git describe upstream/release/v2.18 --abbrev=0
v2.18.2
```

I was wondering how we can solve this issue. Unfortunately, there are many cases to consider and that's why I think the most accurate thing that we can show in the footer would be a version that we provide, i.e. in the package.json file. We try to keep it up to date anyways and for the dev environment it's not that important to see that we are 40 commits since latest release in the footer. We might keep that extra info as a static file (see: https://dev.kubermatic.io/assets/config/version.json).

**Comment by maciaszczykm** [comment]
@xrstf @kubermatic/sig-ui What do you think?

**Comment by maciaszczykm** [comment]
Other idea would be just displaying the commit if the served version is not the tag. In that way everything is automated, we do not get misleading info on dev environment and tags created on release branches would be displayed correctly.
