### ISSUE TITLE
Minimum spot instance price input accepts invalid value?

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#3664]
**What happened?**:
<img width="819" alt="Zrzut ekranu 2021-09-8 o 14 49 10" src="https://user-images.githubusercontent.com/2823399/132512766-5dc51cf8-6021-4c46-adb9-a7c908a2b653.png">

**What should happen?**: Should the field be invalid in that case?

**How to reproduce?**: Go to wizard, pick AWS as provider and select spot instance checkbox.

**Environment**
- UI Version: master
- API Version: master
- Domain: dev
- Others: Chrome on macOS

**Comment by floreks** [comment]
@moadqassem is spot instance price required if spot instance is selected?

**Comment by moadqassem** [comment]
Non of the spot instance configuration should be required. At least from the aws api point of view.

**Comment by floreks** [comment]
Regarding the original issue `0.` is parsed as a `null` since "proper" float number delimiter is a `,`. That's why it is not blocking the next step since it considers this input the same as an empty field.

The main issue here is that the input field of type number does not give us a way to read the raw input, instead we only get already parsed values, and values like `.`, `0.` are visible as `null` in the code. If we'd want to override the `null` to a default or min value then it would result in input value flickering while providing the value by the user. We'd need to completely drop the angular input handling and introduce a low-level component with fully custom logic to handle this. I guess effort would be bigger than the reward in this case as this is rather a small issue, not a blocker.
