### ISSUE TITLE
Investigate Admin Settings Browserwidth Problems

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#3830]
Defaults and Limits breaks at around ~1700px Browserwidth (likely because of Resource Quota line)
![image](https://user-images.githubusercontent.com/49145827/140742665-96198ab0-638b-4c8f-a566-cb9047f1b282.png)

Interface breaks at around ~1600px Browserwidth (likely because of custom links)
![image](https://user-images.githubusercontent.com/49145827/140742834-a85cd930-9bab-49a0-a020-da1e20b87646.png)

The fields have fixed width (I don't know if we want to keep it that way) so one idea is to reduce the width of the inputs, but that probably won't work because of the input labels

The horizontal scrollbar that appears is styled in a way that is barely visible and barely useable so it might as well not exist. This is a problem.

**Comment by floreks** [comment]
Cards currently have a fixed width so that they won't just start randomly rearranging items when being shrunk. In order to have a responsive UI, we'd need separate designs for different breakpoints.

**Comment by Waseem826** [comment]
This doesn't seem to be problematic anymore because the sidebar now auto-collapses at 1500px width and also the input fields wrap at 1200px width.

**Limits Page:**

![screenshot-localhost_8000-2023 05 04-16_59_58](https://user-images.githubusercontent.com/13975988/236197935-79265c5f-bcdd-48ef-9b70-e1541ad50393.png)

**Customization Page:**

![screenshot-localhost_8000-2023 05 04-17_00_19](https://user-images.githubusercontent.com/13975988/236198007-2e1b67c0-7160-446f-a733-ec3961083017.png)
