### ISSUE TITLE
Redesign view loading spinner

### ISSUE THREAD

**Issue by maciaszczykm** [kubermatic/dashboard#4236]
**What is the problem, where is it and why is it an issue?** When loading whole view we often display spinner (i.e. external cluster details). It's very small and centered only horizontally. It would be nice to improve it a bit.

**Suggest how to fix it, if possible**

**Comment by cschieder** [comment]
### Proposed Loading Spinner adjustments

- [ ] Cluster Create, add loadingspinner to provider logos and country flags? alternatively put a grey square that vanishes once the actual logo is there, like a placeholder
- [ ] External Cluster: show buttons, Cluster Card, Machine Deployments and Event card. On Cluster and Machine Deployments show the headline, hourglass and "Loading..." until data is there (this is already on Cluster Details->MD card)
- [ ] ^ same for Cluster, let's make it so the page is not empty with only a loadingspinner but the cards, even if empty, are already there. The buttons too.
- [ ] ^ same for MDs 
- [ ] Service Accounts, upon unfolding a Service account, show the loading spinner inside the rectangle of the table, rather than the table outline only appearing after
- [ ] on slow internet, upon clicking on another sidebar step it feels like it lags for about 0.3 -1 seconds, it does not switch to the other page fast enough and the sidebar active styling is still on the last step for the duration of this delay, can that be adjusted in any way?
