### ISSUE TITLE
Allow allocating floating IPs in exiting OpenStack user clusters

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/dashboard#4581]
### What happened
For OpenStack user clusters it is not possible to request Floating IP by selecting "Allocate Floating IP" when editing an existing Machine Deployment or adding a new Machine deployment to en existing user cluster:

Editing an existing Machine Deployment:

---
![Screenshot 2022-06-10 at 15 24 25](https://user-images.githubusercontent.com/15926980/173076142-6af8f692-530c-495a-bc0e-1863bf718b41.png)
---

Adding a new Machine Deployment:

---
![Screenshot 2022-06-10 at 15 28 42](https://user-images.githubusercontent.com/15926980/173076170-21a1505e-831a-46c9-bb20-407ed69579eb.png)
---

In both cases, the checkbox is disabled and the hover tooltip says "Floating IP usage is enforced by selected datacenter" even if the datacenter has the following spec:

```
      spec:
        openstack:
          enforceFloatingIP: false
```

### Expected behavior
"Allocate Floating IP" checkbox should be disabled only when `enforceFloatingIP` is `true`.

### How to reproduce
Create a user cluster in OpenStack datacenter with `enforceFloatingIP: false`. Do not enable "Allocate Floating IP" during cluster creation. After the cluster is up, try editing the existing Machine Deployment or adding a new Machine Deployment - "Allocate Floating IP" will be disabled.

### Environment
Reported in KKP 2.20.3, reproduced in the latest master as well.

**Comment by rastislavs** [comment]
@Waseem826 this seems to be an API issue then, I would first check if this can be easily fixed in the backend/API without breaking backward compatibility

**Comment by lsviben** [comment]
I found the issue. The API for Cluster creates uses the CRD CloudSpec, and the API model type PublicOpenstackCloudSpec (which is publicly safe), as the return value and for get/list. So when the cluster is being created, the UI sends us the CloudSpec, but when we return it we give the PublicCloudSpec.

And I see that for OpenStack there is a bug, as the Public one has `floatingIpPool` instead of `floatingIPPool`
https://github.com/kubermatic/kubermatic/blob/master/pkg/api/v1/types.go#L1132

**Comment by Waseem826** [comment]
Yea, that difference causes the UI to disable that checkbox since we're checking `floatingIPPool` value and that's `undefined`.
