### ISSUE TITLE
Notification UI/UX Update

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4662]
### Design
https://www.figma.com/file/dJQKgUPzIDND36o2Nq8dct/Loodse-UI?node-id=7287%3A76810
![image](https://user-images.githubusercontent.com/49145827/177790527-992e3d2f-a6fb-46b2-8759-6b1171be2083.png)
### Interface Changes

- [x] new total width of notifications: 400px
- [x] change side bar to red/green circle style, change error icon to ! 
- [x] add counter to bell icon (cap at 99 notifications) 
![image](https://user-images.githubusercontent.com/49145827/177789428-e1bd7d08-a4f4-4f23-91ff-ba7b3ded2e63.png)

### Functionality Changes
- [ ] Introduce a notification cap of 3 - no more than 3 notifications can show at once
- [ ] If possible change timing to be dependent on character amount like 1 character equals every 100 milliseconds(including spaces)
- [x] don't auto-dismiss a notification if it's being hovered
- [x] Errors don't only show the code but a human readable short error headline, this headline needs to be added/be available for error messages. Ideally it sums up the error in a few words. If no specific error message is available show a generic Error headline

### Proposal/Idea
- [ ] On resource created notifications add send to resource functionality hidden as a hyperlink on the resource
![image](https://user-images.githubusercontent.com/49145827/177787513-0bf084d3-316f-47e8-ae7d-8f8956e1defb.png)
- [ ] Maybe move start of notification line higher? this would be to avoid lower located buttons like on cluster create wizard
![image](https://user-images.githubusercontent.com/49145827/177791184-aa93d7e9-fb14-4d77-b361-e5506780b3eb.png)

covers and closes #4545

**Comment by Waseem826** [comment]
>Introduce a notification cap of 3 - no more than 3 notifications can show at once

Unfortunately we cannot display more than 1 notification at a time while using our current Notifications package (Angular Material Snackbar). We'll need to switch to a different package to achieve this and I think that should be done in a separate ticket since its a big change.

> If possible change timing to be dependent on character amount like 1 character equals every 100 milliseconds(including spaces)

IMO this will increase the timing too much since average notification characters length is around 100 characters.

 >On resource created notifications add send to resource functionality hidden as a hyperlink on the resource
 
We redirect the user to newly created resource by default so I think this is not needed.

>Maybe move start of notification line higher? this would be to avoid lower located buttons like on cluster create wizard.

Moving higher might solve the problem in some cases but there will still be pages which have odd height and hence the notification will block content behind it. Also, moving it higher doesn't look good because it leaves too much space below and it looks out of natural position.
