### ISSUE TITLE
Extra space in project tiles with no resource quotas

### ISSUE THREAD

**Issue by Waseem826** [kubermatic/dashboard#4753]
**What is the problem, where is it and why is it an issue?**
If there are no resource quotas for a project then it results in empty space being show in project tiles.

![screenshot-localhost_8000-2022 08 02-14_54_43](https://user-images.githubusercontent.com/13975988/182347253-8d8f9dfd-4511-40e2-9491-8a47432688f2.png)

**Suggest how to fix it, if possible**
We should not add this space if a project has no resource quotas. Or we should display some text here that no quotas are configured for this project.

**Comment by Waseem826** [comment]
@cschieder do you have any suggestions on how to solve this problem?

**Comment by cschieder** [comment]
I was thinking we collapse the space for the cards that don't have quotas, with the caveat that the behavior should be across the whole line

for example
1) has quotas 2) no quota 3) no quota 4) no quota -> all of these are on the same line so the cards are all the same height
5) no quota 6) no quota 7) no quota 8) no quota -> now we can collapse the height down, because none of the cards has a quota 

Additionally I was considering sorting the cards alphabetically but separating them by quotas
1) a 2) b 3) c 4) d -> alphabetical projects with quotas
5) a 6) d 7) e 8) x -> alphabetical projects without quotas

so it might look like
quota, quota, quota quota
quota, no quota, no quota, no quota 
no quota, no quota, no quota, no quota -> from here on the quota space is collapsed

We need to keep in mind that we also separate the projects into 1) native projects and 2) external projects

so both category separations would need to still exist... I'm not sure if this is the best solution let me know what you think @Waseem826

**Comment by Waseem826** [comment]
I'm not sure if it would be easy to sort them on the basis of quotas because quotas are fetched for each project individually and after all projects have been displayed.
I was thinking may be we can display some text instead of empty space. Something like `No quotas configured`. Or would that look too repetitive because initially there would be no project with quotas configured?

**Comment by cschieder** [comment]
I see, okay, yea. Maybe we can only display quotas in the cards after at least one project has them configured? Otherwise this empty state as you proposed:
![image](https://user-images.githubusercontent.com/49145827/182576559-a1205537-7fda-41c7-b4c2-60b8ccb5fcd5.png)

**Comment by Waseem826** [comment]
This sounds good to me and the design looks fine as well.
