### ISSUE TITLE
UI/UX Improvements/Fixes

### ISSUE THREAD

**Issue by cschieder** [kubermatic/dashboard#4788]
- [x] (this is the high priority part) the icons on Cluster page are oddly far inside? it should be the same distance from the right edge of the card as everywhere else
![why are these icons so far inwards](https://user-images.githubusercontent.com/49145827/183031120-7b6cf99f-7e01-4154-b3e3-cf4a5821a310.PNG)

- [ ] item is not clickable, the cursor should not change to pointer
![not clickable so shouldnt have that cursor](https://user-images.githubusercontent.com/49145827/183031099-caa909d6-cb6b-4aeb-b827-9446deccdf10.PNG)

- [x]  Disabled checkboxes should not appear to be filled, the outline should still be visible
![disabled checkbox no outline](https://user-images.githubusercontent.com/49145827/183031155-71bf8624-d63d-4732-b34b-f7688a84b5e5.png)
intended look (last row shows disabled) 
![image](https://user-images.githubusercontent.com/49145827/183357117-2a9f4d68-d010-445d-b3c5-e577d90aa223.png)

**Comment by Waseem826** [comment]
>item is not clickable, the cursor should not change to pointer
1. This is a third party package so pointer cursor is added by that.
2. I think pointer cursor is correct here since a tooltip is displayed on hover, which is same behavior as other places in our application where tooltip is displayed, for example, `i` icons.

Please let me know if you still want this to be changed.
