### ISSUE TITLE
Test RockyLinux OS for supported Cloud Providers - Test Release 2.21

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#4873]
## Testing Procedure

**Support for RockyLinux OS in supported providers**

### Supported Cloud Providers
  - [x] Aws
  - [x] Azure
  - [x] Digital Ocean
  - [x] Equinix
  - [x] Hetzner
  - [x] Kubevirt
  - [x] Openstack
  - [x] VSphere

### Cluster Wizard
- [x] Create wizard from one of the above listed providers
- [x] Initial Nodes step in wizard should display `RockyLinux` OS
- [x] Cluster summary page should show selected `Operating System`

## Acceptance Criteria
- [x] All providers listed above should have `RockyLinux` OS support
- [x] Cluster Wizard initial Nodes page/Cluster Summary page should show selected OS

### Other Features
- [ ] Check the API documentation

**Comment by rastislavs** [comment]
Issues found during testing:
- RockyLinux icon is not shown under "Operating System" in Machine Deployments list on a running cluster:
![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/58c0aa4d-c592-44e6-8c55-17cb41f1151a)
- RockyLinux icon is missing on the machine deployment detail / node details view:
![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/f0761d97-80d8-4e8e-a81e-a905bb3166e3)
- When editing a Machine Deployment, wrong Operating System is pre-selected (Ubuntu instead of Rocky Linux):
![image.png](https://images.zenhubusercontent.com/5f9feacdd87c6f0418bee1e8/6d3d1a59-f436-4650-ac0d-df35edd4e98a)

**Comment by KhizerRehan** [comment]
@rastislavs  `md` spec returning `rockyLinux` instead of `rockylinux` which is the issue on all the places and it will be fixed once it is fixed from backed,
```json
{
    ...
    "spec": {
       "operatingSystem": {
                "rockyLinux": {
				  ...
                }
            },
    },
}

```

**Comment by ahmedwaleedmalik** [comment]
@rastislavs with https://github.com/kubermatic/kubermatic/pull/10835 we have fixed https://github.com/kubermatic/dashboard/issues/4878. You can move forward with testing this.

**Comment by rastislavs** [comment]
Everything works as expected with the fix (https://github.com/kubermatic/kubermatic/pull/10835).
