### ISSUE TITLE
Disable "Open Dashboard" button based on available feature gates

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#5220]
**User story**
As a user, I don't want to click on the "Open Dashboard" button (cluster details page) just to see some vague error message ([more info](https://github.com/kubermatic/kubermatic/issues/11250)).

The culprit here is the Kubernetes Dashboard OIDC integration which has been introduced in KKP 2.21. Now we require `OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin` feature gates to be enabled for the Kubernetes Dashboard to work.

**Acceptance criteria**
- Disable "Open Dashboard" button if `OIDCKubeCfgEndpoint` and `OpenIDAuthPlugin` are missing.
- Add some tooltip to indicate why the functionality is disabled.

**Comment by Talha-Jamil-TJ** [comment]
I and @pkprzekwas had a discussion about this and agreed on the following points,
- Instead of disabling the `Open Dashboard` button, I'll disable the `Enable Kubernetes Dashboard` button in `Admin Settings > Interface`
- `oidcKubeCfgEndpoint` feature gate is already being returned in the API response, @pkprzekwas will add the `OpenIDAuthPlugin` too (it's currently missing)
- Once any of the two feature gates are disabled I'll disable the `Enable Kubernetes Dashboard` checkbox, its value will be set to `false` in the backend.
