### ISSUE TITLE
Replace gts, stylelint and html-beautify with prettier

### ISSUE THREAD

**Issue by Talha-Jamil-TJ** [kubermatic/dashboard#5236]
**What would you like to cleanup?**:
Currently running `npm run fix` is taking too much time to complete because the command is using four packages `gts (Google Typescript Style)`, `stylelint`, `html-beautify` and `license-check-and-add`.
We can replace the first three packages with `prettier`, which drastically increases the speed and we'll have three less packages to maintain too.

#### npm run fix

https://user-images.githubusercontent.com/56511988/200570713-3a5ee9ea-74a7-400e-ab05-60da43342ae4.mov

#### Prettier `prettier --config ./.prettierrc.cjs  --write '**/*.{ts,js,scss,css,html}'`

https://user-images.githubusercontent.com/56511988/200819511-3613a35f-2f5b-4852-8b63-54740a1cac79.mov

Keep in mind this is prettier running on the whole project, we'll only need to format the staged files after the first format

**Comment by KhizerRehan** [comment]
I don't see this ticket as a valid ticket may every package has a different use case how prettier will solve that issue apart from html-beautify i see none of the things that prettier configuration can solve it. Can you answer following queries does prettier solve this thing?

- If any file has missing licence does prettier will add it?
	- can we define multiple formats of formatting of file based on type of extension using prettier?
	 check `license-checker-config.json`
- I need specific configuration for ts, stylelint file does prettier will add it? 
	
As far my experienced and i know prettier adds basic linting and prettier option and it supports multiple languages. 

Following ang Generalized [options](https://prettier.io/docs/en/options.html) are supported.

```
 "trailingComma": "es5",
  "tabWidth": 4,
  "semi": false,
  "singleQuote": true
  ```
 
IMO, `npm: fix` is an npm package IMO dependent on hardware/software specs same command take ages in e.g windows based laptop and fast in Apple/Mac based systems thoughts? Based on Personal experience.

**Comment by KhizerRehan** [comment]
If still you think ti is can be done. I will highly appreciate to have a concrete example DEMO on "angular" generator APP using CLI so that we can all agree and take step to do this ticket if performance is an issue.

- Secondly, from DEV perspective you don't need to run every command each time before every commit i think they can be skipped via skipping or adding new NPM command for DEV purpose and run "npm:fix" command only at end before pushing to remote origin or creating PR.

**Comment by ahmedwaleedmalik** [comment]
@Talha-Jamil-TJ gts uses prettier under the hood. I agree with @KhizerRehan tbh.

**Comment by ahmedwaleedmalik** [comment]
@Talha-Jamil-TJ what's the conclusion for this? Should we close this issue?

**Comment by Talha-Jamil-TJ** [comment]
I want to create a demo PR with the changes I suggest, we can discuss further if those changes are satisfactory or otherwise.

**Comment by ahmedwaleedmalik** [comment]
Demo PR would be nice but before that can you reply to @KhizerRehan's comments? The current problem is that you have not properly explained the details regarding why it's required and IMO you misunderstood how `gts` works. Adding a demo PR wouldn't really help since this issue is more of a proposal and demo PR is only applicable if this proposal is approved.

**Comment by ahmedwaleedmalik** [comment]
> gts (Google Typescript Style), stylelint, html-beautify and license-check-and-add

Which command out of these 4 takes the most time? Why does it take a lot of time? Is it due to our code-base or the way GTS configures it? What command(with flags) is GTS running under the hood for us against that slow command? If we run that command directly(not within GTS) does it take the same amount of time?
