### ISSUE TITLE
Auto-populated values list for selection against the fields under "Settings" tab on the "Provider Presets" screen 

### ISSUE THREAD

**Issue by archups** [kubermatic/dashboard#5405]
### Description of the feature you would like to add / User story

As a end user 
I would like to have auto-populated values list for selection against the fields on the "Provider Presets" screen "Settings" tab when user enters the specific Cloud Provider credentials
in order to have achieve consistent behavior on both Create Cluster and Provider Preset screen in turn improved user experience. 

### Solution details

-  On the Provider Preset "Create Preset" > "Settings" screen, during vSphere preset creation process once the username and password field values are added by the end user, the other fields value list should be fetched based on the credentials match and listed  for user selection. 
- Similar auto-populated list of values for each setting fields should be rendered based on the credentials match for rest of the supported cloud providers too such as AWS, Azure and so on .
- Make the auto-populated list behavior/experience consistent with that on the "Create Cluster" > Settings" screen.

### Use cases

When username and password (in case of vSphere) or Cloud provider credentials are entered, the auto-populated list  for the remaining fields should be fetched and made available for value selection. Expecting similar behavior to the one that works on the Create Cluster >  Settings screen.

**Comment by ahmedwaleedmalik** [comment]
@csengerszabo @archups this is not possible since the presets in the cluster creation wizard depend on the data center information to auto-populate those fields. For example, for vSphere, the cluster name, endpoint, etc. is defined at the seed level. Without that information, it's impossible to load other fields like let's say all the available networks.

Maybe it's possible for a few cloud providers but even then that would make the whole functionality inconsistent from a UI/UX perspective which is not something desirable.
