### ISSUE TITLE
Small Logos after upgrade

### ISSUE THREAD

**Issue by SimonTheLeg** [kubermatic/dashboard#5576]
### What happened

Logos are being resized after upgrading from KKP 2.20.11 to 2.21.4.

Before update
![image](https://user-images.githubusercontent.com/20774623/213492969-89e7aa29-b70e-4f90-92d0-deb2062c908d.png)

After update
![image](https://user-images.githubusercontent.com/20774623/213492995-3d809147-ab79-43ba-8b40-f5f4bbc904fe.png)

### Expected behavior

Logos are not resized

### How to reproduce

- Use the Brave browser in MacOS
- Switch to Kubermatic Dark mode

### Additional Infos

- The issue only seems to occur when choosing Dark mode in KKP
- The issue only seems to only occur in Brave Browser?

It does seem like the values get computed like this from dark.css
![screenshot_edited](https://user-images.githubusercontent.com/20774623/213494415-04decd6e-adba-4abe-bc72-bb220040c481.jpg)
![image](https://user-images.githubusercontent.com/20774623/213494451-b7976c74-da17-4084-8d97-9e4a483050a1.png)

### Environment
- UI Version: 2.21.4
- API Version: 2.21.4

**Comment by ahmedwaleedmalik** [comment]
>The issue only seems to only occur in Brave Browser?

@SimonTheLeg is this issue reproducible on chrome or Mozilla as well for the user?

**Comment by judge-red** [comment]
Hi, "the user" here :)

This problem seems to have fixed itself...I can't reproduce it in Brave anymore. (And just tried Chrome, don't see it there either.) Not sure why exactly, but I strongly suspect a cached `dark.css` from KKP 2.20 was the culprit then.

So I guess the bug here is that `dark.css` should also have a version/random/whatever string in the filename, like `styles.*.css`

Cheers,
Sandro

**Comment by SimonTheLeg** [comment]
understood will close this issue then
