### ISSUE TITLE
KubeVirt MD required fields not respected during update

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/dashboard#5671]
### What happened
I am able to save changes even if the OS field is empty
![image](https://user-images.githubusercontent.com/27352691/217227873-868e7ec1-94c9-41e6-83b4-14e2377465ac.png)

### Expected behavior
Required fields should be respected.

### How to reproduce
* Go to KubeVirt cluster that has MDs created
* Edit one MD
* Choose operating system that doesn't have links defined
* You are able to click save button (but it should not be allowed)

### Environment
- UI Version: v2.22
- API Version: v2.22
- Domain: QA

**Comment by Waseem826** [comment]
The UI doesn't display any value in OS field because there are no dropdown options, however, that value is present behind the scenes in form (taken from already saved MD details) so that's why Save Changes button is not disabled (because form is still valid). But lets keep this issue open so we can check if its possible to change this behaviour.

**Comment by mfranczy** [comment]
> The UI doesn't display any value in OS field because there are no dropdown options

Yes, but the case is to force users to migrate to new MDs, if there is empty list of operating systems users should not be able to edit MDs with old values.
