### ISSUE TITLE
ETCD backups - Test Release 2.24

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/dashboard#6311]

**Comment by ahmadhamzh** [comment]
it seems that all the backups are failed due to a `Job has reached the specified backoff limit`
is that expected ? 
![image](https://github.com/kubermatic/dashboard/assets/85109141/3fd92e21-782d-4606-ac4d-b9e2c52dae13)

also i try to create a backup using `kubctl` and it seems that the object in the docs is not right cause i needed to add spec.name in order to create the `EtcdBackupConfig` object and the field spec.name is not there in the docs, 
also we need to add labels with the project-id 

currently Docs :
![image](https://github.com/kubermatic/dashboard/assets/85109141/4b0b7101-a883-4f4c-b0f7-b444905dfbf5)

should be :
![image](https://github.com/kubermatic/dashboard/assets/85109141/8ac264cc-3e0a-4142-a97d-1ae28b37f995)

**Comment by ahmedwaleedmalik** [comment]
Works as expected.
